### ISSUE TITLE
lanyon   error

### ISSUE THREAD

**Issue by ss7247** [mkaz/lanyon#14]
run  'go build -o lanyon'

chmod 0777 lanyon 

 ./lanyon 
./lanyon: line 1: syntax error near unexpected token `newline'
./lanyon: line 1: `!<arch>'

**Comment by ss7247** [comment]
version : debian 7.0

**Comment by mkaz** [comment]
@ss7247 I've updated the build instructions, they were quite old.
A simple `go get` and then `go build` should be sufficient.
