### ISSUE TITLE
less is not working

### ISSUE THREAD

**Issue by gustavopaes** [mkaz/lanyon#9]
Hi, Good job here. Congrats.

I think the last `lessc` version (2.1.1) don't accept more `--clean-css` parameter. When used, the CSS file is not generated.

I just removed this parameter and less starts work. Line [#231](https://github.com/mkaz/lanyon/blob/master/main.go#L241):

```
cmd := exec.Command(path, "--no-color", "--no-ie-compat", "--silent", "-su=off", "-sm=on", lessfile)
```

Thank you.

**Comment by khimaros** [comment]
The solution here is to `npm install -g less-plugin-clean-css`

@mkaz -- it would probably help to update the documentation since many people will attempt to run Lanyon using the default examples dir.

**Comment by mkaz** [comment]
Thanks @khimaros - I've updated the documentation.
